version: '3.8'
services:
  db:
    image: postgres:15
    container_name: star_postgres
    restart: always
    environment:
      POSTGRES_USER: star_user
      POSTGRES_PASSWORD: star_password
      POSTGRES_DB: star_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: